name: GitHub Check Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install CI dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes clang-format clang-tidy gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Compile src code
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build --parallel
      - name: Clang-format Check
        id: clang_format
        continue-on-error: true
        run: |
          make check-format --keep-going
      - name: Clang-tidy Check
        id: clang_tidy
        if: ${{ always() }}
        continue-on-error: true
        run: |
          make check-tidy --keep-going
      - name: Clang-ASan Check
        id: clang_asan
        if: ${{ always() }}
        continue-on-error: true
        run: |
          make check-asan --keep-going
      - name: Fail if checks failed
        if: ${{ always() && (steps.clang_format.outcome == 'failure' || steps.clang_tidy.outcome == 'failure' ||
            steps.clang_asan.outcome == 'failure') }}
        run: |
          echo "clang-format outcome: ${{ steps.clang_format.outcome }}"
          echo "clang-tidy outcome: ${{ steps.clang_tidy.outcome }}"
          echo "clang_asan outcome: ${{ steps.clang_asan.outcome }}"
          exit 1
      - run: echo "🍏 This job's status is ${{ job.status }}."
